
var api= {"activities":[{"name":"Bar", "url":"https://i.ibb.co/SNkNF9p/bar.jpg"},
{"name":"Réservation", "url":"https://i.ibb.co/JrbhCyJ/booking.jpg"},
{"name":"Bowling", "url":"https://i.ibb.co/hFnj0t7/bowling.jpg"},
{"name":"Ménage", "url":"https://i.ibb.co/SPfm8jy/cleaning.jpg"},
{"name":"Boite de nuit", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Discothèque", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Club", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Nightclub", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Boite", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Danser", "url":"https://i.ibb.co/ZBGy4Ph/club.jpg"},
{"name":"Concert", "url":"https://i.ibb.co/rvYsh7h/concert.jpg"},
{"name":"Coocooning", "url":"https://i.ibb.co/bmB1W5j/coocooning.jpg"},
{"name":"Détente", "url":"https://i.ibb.co/bmB1W5j/coocooning.jpg"},
{"name":"Repos", "url":"https://i.ibb.co/bmB1W5j/coocooning.jpg"},
{"name":"Cuisine", "url":"https://i.ibb.co/DKY7qRX/cooking.jpg"},
{"name":"Do it yourself", "url":"https://i.ibb.co/r2pCRPd/diy.jpg"},
{"name":"Foire", "url":"https://i.ibb.co/T1NVkxv/fair.jpg"},
{"name":"Fete foraine", "url":"https://i.ibb.co/T1NVkxv/fair.jpg"},
{"name":"Bouffe", "url":"https://i.ibb.co/xDLyPx8/eating.jpg"},
{"name":"Manger", "url":"https://i.ibb.co/xDLyPx8/eating.jpg"},
{"name":"Festival", "url":"https://i.ibb.co/PNS4j09/festival.jpg"},
{"name":"Famille", "url":"https://i.ibb.co/Cm0v2jX/family.jpg"},
{"name":"Amis", "url":"https://i.ibb.co/NL4pBhQ/friends.jpg"},
{"name":"Jeux", "url":"https://i.ibb.co/VVRvJb2/game.jpg"},
{"name":"Karaoké", "url":"https://i.ibb.co/HGz7MVB/karaoke.jpg"},
{"name":"Répetition", "url":"https://i.ibb.co/Jy9jJfz/instrument.jpg"},
{"name":"Musique", "url":"https://i.ibb.co/Jy9jJfz/instrument.jpg"},
{"name":"Instrument", "url":"https://i.ibb.co/Jy9jJfz/instrument.jpg"},
{"name":"Couture", "url":"https://i.ibb.co/zGDzKMV/knitting.jpg"},
{"name":"Tricot", "url":"https://i.ibb.co/zGDzKMV/knitting.jpg"},
{"name":"Cours", "url":"https://i.ibb.co/DYmrycm/lesson.jpg"},
{"name":"Ecole", "url":"https://i.ibb.co/DYmrycm/lesson.jpg"},
{"name":"Musée", "url":"https://i.ibb.co/C2N2nd7/museum.jpg"},
{"name":"Match", "url":"https://i.ibb.co/K2Wnf4m/match.jpg"},
{"name":"Regarder match", "url":"https://i.ibb.co/K2Wnf4m/match.jpg"},
{"name":"Regarder le match", "url":"https://i.ibb.co/K2Wnf4m/match.jpg"},
{"name":"Peinture", "url":"https://i.ibb.co/p00gqsX/painting.jpg"},
{"name":"Photographie", "url":"https://i.ibb.co/Qm3xLgm/photography.jpg"},
{"name":"Photo", "url":"https://i.ibb.co/Qm3xLgm/photography.jpg"},
{"name":"Pique nique", "url":"https://i.ibb.co/BCQhLP7/picnic.jpg"},
{"name":"Poterie", "url":"https://i.ibb.co/HT6rRT2/pottery.jpg"},
{"name":"Pyjama", "url":"https://i.ibb.co/1K3m56d/pyjama.jpg"},
{"name":"Pyjama party", "url":"https://i.ibb.co/1K3m56d/pyjama.jpg"},
{"name":"Bricolage", "url":"https://i.ibb.co/5L6RP7z/repair.jpg"},
{"name":"Réparation", "url":"https://i.ibb.co/5L6RP7z/repair.jpg"},
{"name":"Shopping", "url":"https://i.ibb.co/qjzpybX/shopping.jpg"},
{"name":"Courses", "url":"https://i.ibb.co/qjzpybX/shopping.jpg"},
{"name":"Course", "url":"https://i.ibb.co/qjzpybX/shopping.jpg"},
{"name":"Sport", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Fitness", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Exercice", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Cours de sport", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Salle de sport", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Gym", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Salle de gym", "url":"https://i.ibb.co/YDJcVjp/sport.jpg"},
{"name":"Théatre", "url":"https://i.ibb.co/cY48cTF/theater.jpg"},
{"name":"Voyage", "url":"https://i.ibb.co/8BhtT1M/travel.jpg"},
{"name":"Jeux vidéo", "url":"https://i.ibb.co/gmX1BY8/videogame.jpg"},
{"name":"Console", "url":"https://i.ibb.co/gmX1BY8/videogame.jpg"},
{"name":"Visite", "url":"https://i.ibb.co/3dnJPhm/visit.jpg"},
{"name":"Tourisme", "url":"https://i.ibb.co/3dnJPhm/visit.jpg"},
{"name":"Balade", "url":"https://i.ibb.co/NW1XqXr/walk.jpg"},
{"name":"Promenade", "url":"https://i.ibb.co/NW1XqXr/walk.jpg"},
{"name":"Dégustation de vin", "url":"https://i.ibb.co/X4DbCBQ/wine.jpg"},
{"name":"Vin", "url":"https://i.ibb.co/X4DbCBQ/wine.jpg"},
{"name":"Travail", "url":"https://i.ibb.co/N3w6gsp/work.jpg"},
{"name":"Révision", "url":"https://i.ibb.co/N3w6gsp/work.jpg"},
{"name":"Bosser", "url":"https://i.ibb.co/N3w6gsp/work.jpg"},
{"name":"Lecture", "url":"https://i.ibb.co/0JdG5jb/book.jpg"},
{"name":"Séries", "url":"https://i.ibb.co/16CFvY5/series.jpg"},
{"name":"Restaurant", "url":"https://i.ibb.co/k0hzcSN/restaurant.jpg"},
{"name":"Soirée bien-être", "url":"https://i.ibb.co/FqTHywF/spa.jpg"},
{"name":"Cinéma", "url":"https://i.ibb.co/8b5LCbs/cinema.jpg"},
{"name":"Sorties entre amis", "url":"https://i.ibb.co/mGb5FCB/friends.jpg"}
],
"foods":[{"name":"Africain", "url":"https://i.ibb.co/yg6pNSv/african.jpg"},
{"name":"Américain", "url":"https://i.ibb.co/qDZPWXP/american.jpg"},
{"name":"Fast food", "url":"https://i.ibb.co/qDZPWXP/american.jpg"},
{"name":"Bagel", "url":"https://i.ibb.co/7kSFvz0/bagel.jpg"},
{"name":"Asiatique", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Koréen", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Thailandais", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Thai", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Cambodgien", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Japonais", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Tibétain", "url":"https://i.ibb.co/gRT6z6S/asian.jpg"},
{"name":"Barbecue", "url":"https://i.ibb.co/W5GV832/barbecue.jpg"},
{"name":"Francais", "url":"https://i.ibb.co/g9sGTp0/bistro.jpg"},
{"name":"Bistro", "url":"https://i.ibb.co/g9sGTp0/bistro.jpg"},
{"name":"Gateau", "url":"https://i.ibb.co/HDZf9gX/cake.jpg"},
{"name":"Gateaux", "url":"https://i.ibb.co/HDZf9gX/cake.jpg"},
{"name":"Sucrée", "url":"https://i.ibb.co/HDZf9gX/cake.jpg"},
{"name":"Dessert", "url":"https://i.ibb.co/HDZf9gX/cake.jpg"},
{"name":"Céréales", "url":"https://i.ibb.co/XYGK5w4/cereales.jpg"},
{"name":"Charcuterie", "url":"https://i.ibb.co/84MXD8d/charcuterie.jpg"},
{"name":"Charcut", "url":"https://i.ibb.co/84MXD8d/charcuterie.jpg"},
{"name":"Planche de charcuterie", "url":"https://i.ibb.co/84MXD8d/charcuterie.jpg"},
{"name":"Assiette de charcuterie", "url":"https://i.ibb.co/84MXD8d/charcuterie.jpg"},
{"name":"Charcuteries", "url":"https://i.ibb.co/84MXD8d/charcuterie.jpg"},
{"name":"Fromage", "url":"https://i.ibb.co/sQMFQP8/cheese.jpg"},
{"name":"Assiette de fromage", "url":"https://i.ibb.co/sQMFQP8/cheese.jpg"},
{"name":"Planche de fromage", "url":"https://i.ibb.co/sQMFQP8/cheese.jpg"},
{"name":"Fromages", "url":"https://i.ibb.co/sQMFQP8/cheese.jpg"},
{"name":"Poulet", "url":"https://i.ibb.co/r7f6K7t/chicken.jpg"},
{"name":"Frites", "url":"https://i.ibb.co/sgbSs28/chips.jpg"},
{"name":"Crepes", "url":"https://i.ibb.co/0J3d9wG/crepes.jpg"},
{"name":"Chips", "url":"https://i.ibb.co/jzG8rKC/crisps.jpg"},
{"name":"Canard", "url":"https://i.ibb.co/NKG581X/duck.jpg"},
{"name":"Oeufs", "url":"https://i.ibb.co/Yf1SqmJ/eggs.jpg"},
{"name":"Omelette", "url":"https://i.ibb.co/Yf1SqmJ/eggs.jpg"},
{"name":"Felafel", "url":"https://i.ibb.co/c2yfNN5/felafel.jpg"},
{"name":"Falafel", "url":"https://i.ibb.co/c2yfNN5/felafel.jpg"},
{"name":"Poisson", "url":"https://i.ibb.co/s9ghCXq/fish.jpg"},
{"name":"Fondue", "url":"https://i.ibb.co/py5M1qr/fondue.jpg"},
{"name":"Raclette", "url":"https://i.ibb.co/py5M1qr/fondue.jpg"},
{"name":"Gratin", "url":"https://i.ibb.co/Try5Tgs/gratin.jpg"},
{"name":"Greque", "url":"https://i.ibb.co/Tc06pRy/greek.jpg"},
{"name":"Hot dog", "url":"https://i.ibb.co/WHh6Cz2/hot-dog.jpg"},
{"name":"Glace", "url":"https://i.ibb.co/J3y08jp/ice-cream.jpg"},
{"name":"Kebab", "url":"https://i.ibb.co/jyQy5sK/kebab.jpg"},
{"name":"Schwarma", "url":"https://i.ibb.co/jyQy5sK/kebab.jpg"},
{"name":"Mexicain", "url":"https://i.ibb.co/hySFsz5/mexican.jpg"},
{"name":"Tex mex", "url":"https://i.ibb.co/hySFsz5/mexican.jpg"},
{"name":"Tacos", "url":"https://i.ibb.co/hySFsz5/mexican.jpg"},
{"name":"Pates", "url":"https://i.ibb.co/WfPND0s/pasta.jpg"},
{"name":"Spaghetti", "url":"https://i.ibb.co/WfPND0s/pasta.jpg"},
{"name":"Portugais", "url":"https://i.ibb.co/QMSy7TY/portuguese.jpg"},
{"name":"Patates", "url":"https://i.ibb.co/N6MFw0m/potatoes.jpg"},
{"name":"Pommes de terre", "url":"https://i.ibb.co/N6MFw0m/potatoes.jpg"},
{"name":"Pomme de terre", "url":"https://i.ibb.co/N6MFw0m/potatoes.jpg"},
{"name":"Quiche", "url":"https://i.ibb.co/m0CcRsH/quiche.jpg"},
{"name":"Tarte", "url":"https://i.ibb.co/m0CcRsH/quiche.jpg"},
{"name":"Ratatouille", "url":"https://i.ibb.co/3mGGzRF/ratatouille.jpg"},
{"name":"Riz", "url":"https://i.ibb.co/0Zq07pk/rice.jpg"},
{"name":"Sandwich", "url":"https://i.ibb.co/2WvND2x/sandwich.jpg"},
{"name":"Fruits De Mer", "url":"https://i.ibb.co/9Wtg2DC/seafood.jpg"},
{"name":"Soupe", "url":"https://i.ibb.co/N9vfrQG/soup.jpg"},
{"name":"Tapas", "url":"https://i.ibb.co/jwXW70H/tapas.jpg"},
{"name":"Espagnol", "url":"https://i.ibb.co/jwXW70H/tapas.jpg"},
{"name":"Légumes", "url":"https://i.ibb.co/pyjBbHs/vegetables.jpg"},
{"name":"Tajine", "url":"https://i.ibb.co/hdgjDX8/tajine.jpg"},
{"name":"Couscous", "url":"https://i.ibb.co/hdgjDX8/tajine.jpg"},
{"name":"Oriental", "url":"https://i.ibb.co/hdgjDX8/tajine.jpg"},
{"name":"Orientale", "url":"https://i.ibb.co/hdgjDX8/tajine.jpg"},
{"name":"Viande", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Steack", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Boeuf", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Agneau", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Gigot", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Grillades", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Veau", "url":"https://i.ibb.co/LQZsp7G/steack.jpg"},
{"name":"Pizza", "url":"https://i.ibb.co/SwpXqCh/pizza.png"},
{"name":"Burger", "url":"https://i.ibb.co/m43DHZQ/burger.png"},
{"name":"Indien", "url":"https://i.ibb.co/JR4fmS9/indian.jpg"},
{"name":"Chinois", "url":"https://i.ibb.co/6P0TK7M/chinese.jpg"},
{"name":"Salade", "url":"https://i.ibb.co/t4JcSmv/salad.jpg"},
{"name":"Sushi", "url":"https://i.ibb.co/R7R9NTP/sushi.jpg"}
]}
